config/routes.rb
ITourSmart::Application.routes.draw do

  root :to => 'pages#splash'

  match "zendesk/login" => "zendesk#login" # will match /zendesk/login
  match "zendesk/logout" => "zendesk#logout" # will match /zendesk/logout
  
  devise_for :users#, :controllers => {:sessions => 'sessions', :registrations => 'registrations', :confirmations => 'confirmations', :passwords => :passwords, :invitations => "invitations"}
  match "users/vcard/:id" => "vcards#show", :as => :vcard
  match "postal_code/search/:country_code" => "postal_codes#search", :as => :search_postal_code
  match "postal_code/search_city_region" => "postal_codes#search_city_region", :as => :search_city_region
  match "dmo_index" => "organizations#dmo_index"
  
  get "locations/list_by_accuracy" => "locations#list_by_accuracy", :as => :list_by_accuracy_locations
  get "locations/geocode" => "locations#geocode", :as => :geocode_locations
  

  resources :assets
  resources :marker_colors
  resources :account_types

  match 'javascripts/hide_announcement' => 'javascripts#hide_announcement', :as => :hide_announcement

  match 'pages/tweets' => 'pages#tweets'
  match 'chargify/update_subscription' => 'chargify#update_subscription'
  match '/maps' => 'maps#index'
  match '/maps/locate' => 'maps#locate'

  match 'dashboard' => 'users#dashboard'
  
  resources :roles do
    member do
      post 'remove_from_organization', :action => :remove_from_organization
      get 'org_approve', :action => :organization_approve
      get 'org_decline', :action => :organization_decline
      put 'org_approve', :action => :organization_approve
      put 'org_decline', :action => :organization_decline
      put 'user_approve', :action => :user_approve
      put 'user_decline'
      get 'unset_admin'
      get 'set_admin'
    end
    collection do
      put 'update_multiple'
      post 'add_to_organization', :action => :add_to_organization
      put 'add_to_organization_unapproved', :action => :add_to_organization_unapproved
    end
  end
  
  resources :recipients do
    member do
      get 'fancybox_show'
    end
    collection do
      put 'mark_as'
    end
  end

  resources :connections do
    get 'find_connections', :on => :collection
    post 'find_connections', :on => :collection
    post 'update_conection', :on => :collection
    get 'list_connections', :on => :collection
    collection do
      get 'inner_circle'
      get 'requested'
    end
  end
  
  resources :memberships do
    member do
      post 'mark', :action => :mark
    end
  end

  resources :account_types
  resources :announcements
  resources :attachments
  resources :categories
  resources :connections
  resources :notes
  resources :organizations do
    collection do
      get 'featured'
      get 'update_category_select/:id', :action => :update_category_select
      get 'list_by_trial'
    end
    member do
      post 'new'
      put 'account/update', :action => :update_account_admin
      post 'mark_as_closed', :action => :mark_as_closed
      post 'unmark_as_closed', :action => :unmark_as_closed
      post 'designate_as_member', :action => :designate_as_member
      post 'undesignate_as_member', :action => :undesignate_as_member
      post 'make_featured', :action => :make_featured
      get 'update_category_select', :action => :update_category_select
      get 'cancel'
      put 'unclaim'
      get 'claim', :action => :edit
      get 'transactions'
      get 'subscriptions'
      put 'migrate'
      get 'change_card'
      put 'update_card'
      get 'signup'
      get 'upgrade'
    end

    resources :inventory_items do
      member do
      end
    end

    resources :locations do
      member do
      end
    end
  end

  resources :pages

  resources :users do
    member do
      get 'dashboard'
      get 'edit_email_preferences'
    end
  end

  scope 'blog' do
    resources :posts, :controller => 'blog_posts', :as => 'blog_posts' do
      resources :comments, :controller => 'blog_comments', :as => 'blog_comments'
      resources :images, :controller =>'blog_images', :as => 'blog_images'
      collection do
        get :drafts
      end
      member do
        get :tag
      end
    end
  end
  match 'blog' => 'blog_posts#index'

  match ':permalink' => 'pages#show'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  validates :message, :presence => true
  validates :starts_at, :presence => true
  validates :ends_at, :presence => true
  scope :active, lambda { { :conditions => ['starts_at <= ? AND ends_at >= ?', Time.now.utc, Time.now.utc] } }
  scope :since, lambda { |hide_time| { :conditions => (hide_time ? ['updated_at > ? OR starts_at > ?', hide_time.utc, hide_time.utc] : nil) } }
  

  def self.current_announcements(hide_time)
    active.since(hide_time)
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < InheritedResources::Base
  #Devise Authentication
  before_filter :authenticate_user!
    
  
  load_and_authorize_resource


  def create
    create!{announcements_url}
  end
  def update
    update!{announcements_url}
  end


end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.haml
= simple_form_for @announcement do |f|
  = f.error_notification
  = f.input :message
  = f.input :starts_at
  = f.input :ends_at
  = render "/generic/action", :f => f

app/views/announcements/_index_list.html.haml
%table.left
  %tr
    %th Message
    %th Starts At
    %th Ends At
    %th
  - for announcement in @announcements
    %tr
      %td= announcement.message
      %td= announcement.starts_at
      %td= announcement.ends_at
      %td= link_to "edit", edit_announcement_path(announcement)

app/views/announcements/edit.html.haml
- title "Edit Site-Wide Announcement"
#content_wrapper
  #full_col.shadow.dark_text
    .col_head
      %h2.float_left
        = "edit site-wide announcement"
      .right
        = link_to "View All", announcements_path
      .clear
    .block_quote.left
      = render 'form'

app/views/announcements/index.html.haml
- title "Site-wide Announcements"
#content_wrapper
  #full_col.shadow.dark_text
    .col_head
      %h2.float_left
        = "site-wide announcements"
      .right
        = link_to "Add a New Site-wide Announcement", new_announcement_path
        |
        = link_to "Dashboard", dashboard_path
      .clear
    .block_quote
      = render 'index_list'

app/views/announcements/new.html.haml
- title "New Announcement"
#content_wrapper
  #full_col.shadow.dark_text
    .col_head
      %h2.float_left
        = "new announcement"
      .right
        = link_to "View All", announcements_path
      .clear
    .block_quote.left
      = render 'form'