config/routes.rb
ITourSmart::Application.routes.draw do

  root :to => 'pages#splash'

  match "zendesk/login" => "zendesk#login" # will match /zendesk/login
  match "zendesk/logout" => "zendesk#logout" # will match /zendesk/logout
  
  devise_for :users#, :controllers => {:sessions => 'sessions', :registrations => 'registrations', :confirmations => 'confirmations', :passwords => :passwords, :invitations => "invitations"}
  match "users/vcard/:id" => "vcards#show", :as => :vcard
  match "postal_code/search/:country_code" => "postal_codes#search", :as => :search_postal_code
  match "postal_code/search_city_region" => "postal_codes#search_city_region", :as => :search_city_region
  match "dmo_index" => "organizations#dmo_index"
  
  get "locations/list_by_accuracy" => "locations#list_by_accuracy", :as => :list_by_accuracy_locations
  get "locations/geocode" => "locations#geocode", :as => :geocode_locations
  

  resources :assets
  resources :marker_colors
  resources :account_types

  match 'javascripts/hide_announcement' => 'javascripts#hide_announcement', :as => :hide_announcement

  match 'pages/tweets' => 'pages#tweets'
  match 'chargify/update_subscription' => 'chargify#update_subscription'
  match '/maps' => 'maps#index'
  match '/maps/locate' => 'maps#locate'

  match 'dashboard' => 'users#dashboard'
  
  resources :roles do
    member do
      post 'remove_from_organization', :action => :remove_from_organization
      get 'org_approve', :action => :organization_approve
      get 'org_decline', :action => :organization_decline
      put 'org_approve', :action => :organization_approve
      put 'org_decline', :action => :organization_decline
      put 'user_approve', :action => :user_approve
      put 'user_decline'
      get 'unset_admin'
      get 'set_admin'
    end
    collection do
      put 'update_multiple'
      post 'add_to_organization', :action => :add_to_organization
      put 'add_to_organization_unapproved', :action => :add_to_organization_unapproved
    end
  end
  
  resources :recipients do
    member do
      get 'fancybox_show'
    end
    collection do
      put 'mark_as'
    end
  end

  resources :connections do
    get 'find_connections', :on => :collection
    post 'find_connections', :on => :collection
    post 'update_conection', :on => :collection
    get 'list_connections', :on => :collection
    collection do
      get 'inner_circle'
      get 'requested'
    end
  end
  
  resources :memberships do
    member do
      post 'mark', :action => :mark
    end
  end

  resources :account_types
  resources :announcements
  resources :attachments
  resources :categories
  resources :connections
  resources :notes
  resources :organizations do
    collection do
      get 'featured'
      get 'update_category_select/:id', :action => :update_category_select
      get 'list_by_trial'
    end
    member do
      post 'new'
      put 'account/update', :action => :update_account_admin
      post 'mark_as_closed', :action => :mark_as_closed
      post 'unmark_as_closed', :action => :unmark_as_closed
      post 'designate_as_member', :action => :designate_as_member
      post 'undesignate_as_member', :action => :undesignate_as_member
      post 'make_featured', :action => :make_featured
      get 'update_category_select', :action => :update_category_select
      get 'cancel'
      put 'unclaim'
      get 'claim', :action => :edit
      get 'transactions'
      get 'subscriptions'
      put 'migrate'
      get 'change_card'
      put 'update_card'
      get 'signup'
      get 'upgrade'
    end

    resources :inventory_items do
      member do
      end
    end

    resources :locations do
      member do
      end
    end
  end

  resources :pages

  resources :users do
    member do
      get 'dashboard'
      get 'edit_email_preferences'
    end
  end

  scope 'blog' do
    resources :posts, :controller => 'blog_posts', :as => 'blog_posts' do
      resources :comments, :controller => 'blog_comments', :as => 'blog_comments'
      resources :images, :controller =>'blog_images', :as => 'blog_images'
      collection do
        get :drafts
      end
      member do
        get :tag
      end
    end
  end
  match 'blog' => 'blog_posts#index'

  match ':permalink' => 'pages#show'

end

app/models/map.rb
class Map
end

app/controllers/maps_controller.rb
class MapsController < LocationSearchController
  #Devise Authentication
  before_filter :authenticate_user!
    

  load_and_authorize_resource

  def index
    filtered_search if filtered_search?
    load_filter_data unless request.xhr?

    respond_to do |format|
      format.html
      format.js { render :partial => 'maps/search_result', :layout => false }
    end
  end

end

app/views/maps/_inventory_item_location_with_pricing_fields.html.haml
- f.object.build_price(:retail_low => number_with_precision(@inventory_item.price.retail_low, :precision => 2), :retail_high => number_with_precision(@inventory_item.price.retail_high, :precision => 2), :price_low => number_with_precision(@inventory_item.price.price_low, :precision => 2), :price_high => number_with_precision(@inventory_item.price.price_high, :precision => 2)) unless f.object.price

= organization = f.object.organization
  
%tr.fields
  %td
    = f.select(:location_id, Location.all.collect {|p| [ p.name, p.id ] }, { :include_blank => true })
  = f.fields_for :price do |p|
    %td.input_low
      = p.text_field :retail_low
    %td.no_border
      = "to"
    %td.input_high
      = p.text_field :retail_high
    %td.input_low
      = p.text_field :price_low
    %td.no_border
      = "to"
    %td.input_high
      = p.text_field :price_high
    %td
      = remove_child_link "remove", f

app/views/maps/_search_map.html.haml
= google_map

= content_for :on_ready do
  - if @locations.blank?
    :plain
      show_google_maps();

#map_canvas

app/views/maps/_search_refine.html.haml
.shadow.smaller
  .col_head
    %h2.float_left
      Search
    .right.even_smaller
      = link_to_function "+/-", "$('#maps_search_refine').toggle()"
    .clear

  = form_tag maps_path, :method => 'get', :id => 'search' do
    = render 'generic/search_refine'

app/views/maps/_search_result.html.haml
- if @locations.present?
  :javascript
    jQuery(function($) {
      show_markers_on_page(#{generate_markers_json(@locations)}, true);
    });
- else
  :javascript
    jQuery(function($) {
      show_google_maps();
    });

- if @locations.present?
  = render 'generic/pagination_info', :entries => @locations

.block_quote.left
  %div
    = render 'users/supplier_list'
.clear

- if @locations.present?
  = render 'generic/pagination_full', :entries => @locations

app/views/maps/index.html.haml
- title "Smart Map"
- stylesheet 'jquery-ui-1.8.6.custom'
- content_for :on_ready do
  :plain
    $("#tabs").tabs();

#leftbar.justify
  = render 'search_refine'

#rightbar.justify
  = render 'generic/banner_1'
  = render 'generic/banner_2'


#middle
  #main_col.shadow.smaller
    .col_head
      %h2.float_left
        = "Smart Map"
      .right.even_smaller
        = link_to_function "+/-", "$('#maps_wrapper').toggle()"
      .pad_10

    #maps_wrapper
      #tabs
        %ul
          %li
            = link_to "Map", "#tabs-1"
          %li
            = link_to "Location", "#tabs-2"
        .clear
        #tabs-1
          .fullmaps
            = render 'search_map'
        .clear
        #tabs-2
          .search_wrapper
            #maps_search_result
              = render 'search_result'
            .clear
      .clear

app/views/maps/locate.json.haml
!={'data' => @locations.collect{|c| {:id => c.id, :name => escape_javascript(c.organization.name + " " + c.name), :address => escape_javascript(c.map_address), :accuracy => c.accuracy, :lat => c.lat, :lng => c.lng, :organization_type=>getOrganizationType(c.organization) }}, :l => '111'}.to_json