config/routes.rb
ITourSmart::Application.routes.draw do

  root :to => 'pages#splash'

  match "zendesk/login" => "zendesk#login" # will match /zendesk/login
  match "zendesk/logout" => "zendesk#logout" # will match /zendesk/logout
  
  devise_for :users#, :controllers => {:sessions => 'sessions', :registrations => 'registrations', :confirmations => 'confirmations', :passwords => :passwords, :invitations => "invitations"}
  match "users/vcard/:id" => "vcards#show", :as => :vcard
  match "postal_code/search/:country_code" => "postal_codes#search", :as => :search_postal_code
  match "postal_code/search_city_region" => "postal_codes#search_city_region", :as => :search_city_region
  match "dmo_index" => "organizations#dmo_index"
  
  get "locations/list_by_accuracy" => "locations#list_by_accuracy", :as => :list_by_accuracy_locations
  get "locations/geocode" => "locations#geocode", :as => :geocode_locations
  

  resources :assets
  resources :marker_colors
  resources :account_types

  match 'javascripts/hide_announcement' => 'javascripts#hide_announcement', :as => :hide_announcement

  match 'pages/tweets' => 'pages#tweets'
  match 'chargify/update_subscription' => 'chargify#update_subscription'
  match '/maps' => 'maps#index'
  match '/maps/locate' => 'maps#locate'

  match 'dashboard' => 'users#dashboard'
  
  resources :roles do
    member do
      post 'remove_from_organization', :action => :remove_from_organization
      get 'org_approve', :action => :organization_approve
      get 'org_decline', :action => :organization_decline
      put 'org_approve', :action => :organization_approve
      put 'org_decline', :action => :organization_decline
      put 'user_approve', :action => :user_approve
      put 'user_decline'
      get 'unset_admin'
      get 'set_admin'
    end
    collection do
      put 'update_multiple'
      post 'add_to_organization', :action => :add_to_organization
      put 'add_to_organization_unapproved', :action => :add_to_organization_unapproved
    end
  end
  
  resources :recipients do
    member do
      get 'fancybox_show'
    end
    collection do
      put 'mark_as'
    end
  end

  resources :connections do
    get 'find_connections', :on => :collection
    post 'find_connections', :on => :collection
    post 'update_conection', :on => :collection
    get 'list_connections', :on => :collection
    collection do
      get 'inner_circle'
      get 'requested'
    end
  end
  
  resources :memberships do
    member do
      post 'mark', :action => :mark
    end
  end

  resources :account_types
  resources :announcements
  resources :attachments
  resources :categories
  resources :connections
  resources :notes
  resources :organizations do
    collection do
      get 'featured'
      get 'update_category_select/:id', :action => :update_category_select
      get 'list_by_trial'
    end
    member do
      post 'new'
      put 'account/update', :action => :update_account_admin
      post 'mark_as_closed', :action => :mark_as_closed
      post 'unmark_as_closed', :action => :unmark_as_closed
      post 'designate_as_member', :action => :designate_as_member
      post 'undesignate_as_member', :action => :undesignate_as_member
      post 'make_featured', :action => :make_featured
      get 'update_category_select', :action => :update_category_select
      get 'cancel'
      put 'unclaim'
      get 'claim', :action => :edit
      get 'transactions'
      get 'subscriptions'
      put 'migrate'
      get 'change_card'
      put 'update_card'
      get 'signup'
      get 'upgrade'
    end

    resources :inventory_items do
      member do
      end
    end

    resources :locations do
      member do
      end
    end
  end

  resources :pages

  resources :users do
    member do
      get 'dashboard'
      get 'edit_email_preferences'
    end
  end

  scope 'blog' do
    resources :posts, :controller => 'blog_posts', :as => 'blog_posts' do
      resources :comments, :controller => 'blog_comments', :as => 'blog_comments'
      resources :images, :controller =>'blog_images', :as => 'blog_images'
      collection do
        get :drafts
      end
      member do
        get :tag
      end
    end
  end
  match 'blog' => 'blog_posts#index'

  match ':permalink' => 'pages#show'

end

app/models/note.rb
class Note < ActiveRecord::Base
  has_many :users, :through => :recipient
  has_many :recipients
  belongs_to :sender, :class_name => 'User', :foreign_key => :sender_id
  accepts_nested_attributes_for :recipients
  
  default_scope order('updated_at DESC')
  
  scope :unread, :conditions => {:is_read => false}
  scope :not_deleted, :joins => :recipients, :conditions => "recipients.is_deleted IS FALSE"
  
  before_save :set_occurred_at
  
  
  def set_occurred_at
    self.occurred_at = Time.now
  end
  
 
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :note
  belongs_to :user
  belongs_to :role
 default_scope order('recipients.created_at DESC')
  scope :inbox, lambda {
    where("is_deleted IS false AND notes.is_sysmessage IS false", includes(:notes))
  }
  scope :notifications, lambda {
    where("is_deleted IS false AND notes.is_sysmessage IS true", includes(:notes))
  }
  
  scope :active, lambda {
    where("is_deleted IS false", includes(:notes))
  }
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  #Devise Authentication
  before_filter :authenticate_user!
    

  #CanCan Authorization
    load_and_authorize_resource
    skip_authorization_check :only => [:fancybox_show]
  
  # GET /recipients
  # GET /recipients.xml
  def index
    @user = current_user
    @recipients = Recipient.where(:user_id => current_user.id).includes(:note)
    respond_to do |format|
      format.html # index.html.haml
      format.xml  { render :xml => @recipients }
    end
  end

  # GET /recipients/1
  # GET /recipients/1.xml
  def show
    @recipient = Recipient.find(params[:id])
    @recipient.update_attributes(:is_read => true)

    respond_to do |format|
      format.html
      format.xml  { render :xml => @recipient }
    end
  end
  
  def fancybox_show
    @recipient = Recipient.find(params[:id])
    @recipient.update_attributes(:is_read => true)

    respond_to do |format|
      format.html { render :layout => false }
      format.xml  { render :xml => @recipient }
    end
  end

  # GET /recipients/new
  # GET /recipients/new.xml
  def new
    @recipient = Recipient.new

    respond_to do |format|
      format.html # new.html.haml
      format.xml  { render :xml => @recipient }
    end
  end

  # GET /recipients/1/edit
  def edit
    @recipient = Recipient.find(params[:id])
  end

  # POST /recipients
  # POST /recipients.xml
  def create
    @recipient = Recipient.new(params[:recipient])
    respond_to do |format|
      if @recipient.save
        if @recipient.user.email_messages == true
          SystemMessageMailer.new_message_email(@recipient).deliver
        end
        format.html { redirect_to(@recipient, :notice => 'Recipient was successfully created.') }
        format.xml  { render :xml => @recipient, :status => :created, :location => @recipient }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipients/1
  # PUT /recipients/1.xml
  def update
    @recipient = Recipient.find(params[:id])

    respond_to do |format|
      if @recipient.update_attributes(params[:recipient])
        format.html { redirect_to(@recipient, :notice => 'Recipient was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.xml
  def destroy
    @recipient = Recipient.find(params[:id])
    @recipient.update_attribute(:is_deleted, true)

    respond_to do |format|
      format.html { redirect_to after_sign_in_path_for(current_user),  :notice => 'Note successfully deleted.'
 }
      format.xml  { head :ok }
    end
  end
  
  
  def mark_as
    if params[:commit] == "Mark as read"
      Recipient.update_all({:is_read => true}, :id => params[:recipient_ids])
    elsif params[:commit] == "Mark as unread"
      Recipient.update_all({:is_read => false}, :id => params[:recipient_ids])
    elsif params[:commit] == "Delete"
      Recipient.update_all({:is_read => true, :is_deleted => true}, :id => params[:recipient_ids])
    end
    redirect_to :back
  end

end

app/views/recipients/_inbox.html.haml
- @recipients = @recipients.inbox.paginate(:per_page => 10, :page => params[:recipients_page])
.block_quote.left
  = will_paginate(@recipients, :param_name => "recipients_page")
  .pad_10
  = form_tag mark_as_recipients_path, :method => :put do
    %table#notes
      - for recipient in @recipients do 
        - if !recipient.is_read
          %tr.notes_unread
            %td.note_checkbox
              = check_box_tag "recipient_ids[]", recipient.id
            %td.note_from
              - if !recipient.note.is_sysmessage
                = link_to recipient.note.sender.name_first, user_path(recipient.note.sender), :class => "note_unread"
              - else
                = "iTourSmart Admin"
            %td.note_message
              .inline
                = link_to recipient.note.subject, recipient, :class => "note_unread"
              = " - " if recipient.note && !recipient.note.body.blank?
              = auto_link(truncate(recipient.note.body, :length => (100 - recipient.note.subject.length)).html_safe) if recipient.note.body
            %td.note_received
              = distance_of_time_in_words(recipient.created_at, Time.now) + " ago"
        - else
          %tr.notes_read
            %td.note_checkbox
              = check_box_tag "recipient_ids[]", recipient.id
            %td.note_from
              - if !recipient.note.is_sysmessage
                = link_to recipient.note.sender.name_first, recipient, :class => "note_read"
              - else
                = "iTourSmart Admin"
            %td.note_message
              .inline
                = link_to recipient.note.subject, recipient, :class => "note_read"
              = " - " if recipient.note && !recipient.note.body.blank?
              = auto_link(truncate(recipient.note.body, :length => (100 - recipient.note.subject.length)).html_safe) if recipient.note.body
            %td.note_received
              = distance_of_time_in_words(recipient.created_at, Time.now) + " ago"
    .block_quote
      = submit_tag "Mark as read"
      = submit_tag "Mark as unread"
      = submit_tag "Delete"
      
      = will_paginate(@recipients, :param_name => "recipients_page")
      .clear

app/views/recipients/_invitation.html.haml
%p
  = "You have been invited to join the #{@recipient.role.organization.name} team."
%p
  = auto_link("Click #{link_to 'here', user_approve_role_path(@recipient.role.id), :method => :put} to accept.".html_safe)
%p.smaller
= auto_link("Or, click #{link_to 'here', user_decline_role_path(@recipient.role.id), :method => :put} to decline and block future invitations from this organization.".html_safe)

app/views/recipients/_list.html.haml
- if @user.recipients.active.count > 0
  - @recipients = @user.recipients.active.paginate(:per_page => 10, :page => params[:recipients_page], :order => "created_at DESC")
  #main_col.shadow.dark_text
    .col_head
      %h2.float_left
        messages
      .col_head_link
        = link_to "message center", recipients_path(:partial => "inbox")
        |
        = link_to "email preferences", edit_email_preferences_user_path(current_user)
      .even_smaller.right
        = link_to_function "+/-", "$('#recipients').toggle()"
        .clear
      .clear
    #recipients
      .block_quote.left
        .pad_10
        = form_tag mark_as_recipients_path, :method => :put do
          %table#note.collapse
            - for recipient in @recipients do
              %tr
                %td.note_checkbox.dashed.note
                  = check_box_tag "recipient_ids[]", recipient.id
                %td.note_from.dashed.note
                  - if !recipient.note.is_sysmessage
                    = recipient.note.sender.name_first
                  - else
                    = "iTourSmart Admin"
                %td.note_message.dashed.note
                  .inline
                    - if recipient.note.is_fancybox_autoload && !recipient.is_read
                      = link_to recipient.note.subject, fancybox_show_recipient_path(recipient.id), :class => "note_unread fancybox_autoload fancybox_inline"
                    - elsif !recipient.is_read
                      = link_to recipient.note.subject, fancybox_show_recipient_path(recipient.id), :class => "note_unread fancybox_inline"
                    - else
                      = link_to recipient.note.subject, fancybox_show_recipient_path(recipient.id), :class => "note_read fancybox_inline"
                  - if recipient.note.body
                    = " - "
                    = truncate(recipient.note.body.gsub(/<\/?[^>]*>/,  ""), :length => (100 - recipient.note.subject.length))
                %td.note_received.dashed.note
                  = distance_of_time_in_words(recipient.created_at, Time.now) + " ago"
          .block_quote
            = submit_tag "Mark as read"
            = submit_tag "Mark as unread"
            = submit_tag "Delete"
        
            = will_paginate(@recipients, :param_name => "recipients_page")
            .clear
- else
  #main_col.shadow.dark_text
    .col_head
      %h2.float_left
        messages
      .col_head_link
        = link_to "Message Center", recipients_path(:partial => "inbox")
        |
        = link_to "Email Preferences", edit_email_preferences_user_path(current_user)
      .even_smaller.right
        = link_to_function "+/-", "$('#recipients').toggle()"
        .clear
      .clear
    #recipients
      .block_quote.left
        .note
          You do not have any new messages.

app/views/recipients/_notifications.html.haml
- @recipients = @recipients.notifications.paginate(:per_page => 10, :page => params[:recipients_page])
.block_quote.left
  = will_paginate(@recipients, :param_name => "recipients_page")
  .pad_10
  = form_tag mark_as_recipients_path, :method => :put do
    %table#notes
      - for recipient in @recipients do 
        - if !recipient.is_read
          %tr.notes_unread
            %td.note_checkbox
              = check_box_tag "recipient_ids[]", recipient.id
            %td.note_from
              - if !recipient.note.is_sysmessage
                = link_to recipient.note.sender.name_first, recipient, :class => "note_unread"
              - else
                = "iTourSmart Admin"
            %td.note_message
              .inline
                = link_to recipient.note.subject, recipient, :class => "note_unread"
              = " - " if recipient.note && !recipient.note.body.blank?
              = auto_link(truncate(recipient.note.body, :length => (100 - recipient.note.subject.length)).html_safe) if recipient.note && !recipient.note.body.blank?
            %td.note_received
              = distance_of_time_in_words(recipient.created_at, Time.now) + " ago"
        - else
          %tr.notes_read
            %td.note_checkbox
              = check_box_tag "recipient_ids[]", recipient.id
            %td.note_from
              - if !recipient.note.is_sysmessage
                = link_to recipient.note.sender.name_first, recipient, :class => "note_read"
              - else
                = "iTourSmart Admin"
            %td.note_message
              .inline
                = link_to recipient.note.subject, recipient, :class => "note_read"
              = " - " if recipient.note && !recipient.note.body.blank?
              = auto_link(truncate(recipient.note.body, :length => (100 - recipient.note.subject.length)).html_safe) if recipient.note && !recipient.note.body.blank?
            %td.note_received
              = distance_of_time_in_words(recipient.created_at, Time.now) + " ago"
    .block_quote
      = submit_tag "Mark as read"
      = submit_tag "Mark as unread"
      = submit_tag "Delete"
      
      = will_paginate(@recipients, :param_name => "recipients_page")
      .clear

app/views/recipients/_sent.html.haml
- @notes = current_user.sent_notes.not_deleted.paginate(:per_page => 10, :page => params[:notes_page], :order => 'notes.updated_at DESC')
.block_quote.left
  = will_paginate(@notes, :param_name => "notes_page")
  .pad_10
  = form_tag mark_as_recipients_path, :method => :put do
    %table#notes
      - for note in @notes do
        - recipient = note.recipients.last
        %tr.notes_read
          %td.note_checkbox
            = check_box_tag "recipient_ids[]", recipient.id
          %td.note_from
            = recipient.user.try(:full_name) if recipient.try(:user)
          %td.note_message
            .inline
              = link_to note.subject, note, :class => "note_read"
            = " - " if note && !note.body.blank?
            = auto_link(truncate(note.body, :length => (100 - note.subject.length)).html_safe)
          %td.note_received
            = distance_of_time_in_words(note.created_at, Time.now) + " ago"
    .block_quote
      = submit_tag "Delete"
    
    = will_paginate(@notes, :param_name => "notes_page")
    .clear

app/views/recipients/_travel_planner.html.haml
- closing = ['Corey and Patrick', 'Patrick and Corey']
%p
  = "#{@recipient.user.name_first},"
%p.pad_10
  = "As a Professional Travel Planner, the use of iTourSmart is complimentary.  All we ask is that you update your profile from time to time.  So, feel free to add your team members, upload your logo, and enjoy everything that iTourSmart has to offer!"
%p.pad_10
  = "We are thrilled that YOU are here,"
%p
  = closing[rand(closing.length)]

app/views/recipients/_trial.html.haml
- closing = ['Corey and Patrick', 'Patrick and Corey']
%p
  = "#{@recipient.user.name_first},"
%p.pad_10
  = "We couldn't think of a better way for you to understand the benefits of iTourSmart than to let you kick the tires for a while.  For that reason, we have set you up with a 30 day trial of our Premium Subscription for free (a $75 USD value).  So feel free to explore everything we have to offer for the next month."
  
%p.pad_10
  = "Once you have had a chance to see which aspects of iTourSmart could be beneficial to you, please adjust your account settings to the appropriate subscription type."
  
%p.pad_10
  = "We will send you a reminder email as the end of your trial nears.  So for now, don't sweat the details, just enjoy the iTourSmart community."
%p.pad_10
  = "We are so happy YOU are here,"
%p
  = closing[rand(closing.length)]

app/views/recipients/_user_request.html.haml
- closing = ['Corey and Patrick', 'Patrick and Corey']
- if @recipient.role
  %p
    = "#{@recipient.user.name_first},"
  %br
  %p
    = "#{@recipient.note.sender.full_name} is requesting to join the #{@recipient.role.organization.name} team.  You can approve (or decline) this request here:"
  %ul.no_bullets
    %li
      = link_to "Add to team", org_approve_role_url(@recipient.role_id), :method => :put
    %li
      = link_to "Decline request to join team", org_decline_role_url(@recipient.role_id), :method => :put  
  %p.pad_10 
  
    =  auto_link("Or, click #{link_to 'here', roles_url(:organization_id => @recipient.role.organization_id)} to see this (and any other) requests to join your team.".html_safe)
- else
  %p
    = "#{@recipient.user.name_first},"
  %br
  %p
    = "#{@recipient.note.sender.full_name} had requested to join yur team, but the request is now void.  Feel free to delete this message."
%br
%p
  = "Have a great day,"
%p
  = closing[rand(closing.length)]

app/views/recipients/_welcome.html.haml
- domain = @recipient.user.email.split("@").last
- closing = ['Corey and Patrick', 'Patrick and Corey']
- if @recipient.user.is_travel_planner?
  %p
    = "#{@recipient.user.name_first},"
  %p
    = "Welcome to iTourSmart, the fastest way to find and connect with travel suppliers.  In an effort to get the most from your experience, please take a moment to:"
  %ul        
    - unless !@recipient.user.roles.empty?
      %li
        %h4
          = auto_link("Setup/update your brand profile".html_safe)
          - Organization.where("url = ? OR aba_email = ? OR syta_email = ?", "www."+ domain, @recipient.user.email, @recipient.user.email).each do |a|
            - if !a.owner_id
              .indent_10.pad_10
                .upgrade
                  .bold.indent_10
                    = "Is #{a.name} your brand?"
                  .even_smaller.indent_10
                    = auto_link("If so, click #{link_to 'here', organization_path(a)} to claim it!".html_safe)
                .pad_5
            - else
              .indent_10.pad_10
                .upgrade
                  .bold.indent_10
                    = "Do you work at #{a.name}?"
                  .even_smaller.indent_10
                    = auto_link("If so, click #{link_to 'here', organization_path(a)} to join the team!".html_safe)
                .pad_5
    - else
      %li
        %h4
          = auto_link"Check out #{link_to @recipient.user.organizations.last.name, organization_path(@recipient.user.organizations.last)}".html_safe
    %li
      %h4
        = auto_link("Setup your #{link_to 'personal profile', edit_user_path(current_user)}".html_safe)          
  %p
    = "We have spent countless hours to ensure that iTourSmart is a tool that will increase your productivity, make your life easier, and hopefully bring a smile to your face once in a while.  That said, we are always looking for ways to improve. So, if something doesn't work, doesn't do what you want it to do, or you can think of an improvement to be implemented in the future - just click the link for 'support' in the title bar above and let us know."
  %p
    = "Enjoy,"
  %p
    = closing[rand(closing.length)]

- else
  %p
    = "#{@recipient.user.name_first},"
  %p
    = "Welcome to iTourSmart, an online community for the Tour and Travel industry.  With over 1,100 Professional Travel Planners and 3,000+ travel suppliers represented, iTourSmart is THE place to find and connect with your customer base.  Getting started is as easy as 1-2-3!"

  %ul
    - unless !@recipient.user.roles.empty?
      %li
        %h4
          = auto_link("Step 1: Setup/update your brand profile".html_safe)
          - Organization.where("url = ? OR aba_email = ? OR syta_email = ?", "www."+ domain, @recipient.user.email, @recipient.user.email).each do |a|
            - if !a.owner_id
              .indent_10.pad_10
                .upgrade
                  .bold.indent_10
                    = "Is #{a.name} your #{a.entity.downcase}?"
                  .even_smaller.indent_10
                    = auto_link("If so, click #{link_to 'here', organization_path(a)} to claim it!".html_safe)
                .pad_5
            - else
              .indent_10.pad_10
                .upgrade
                  .bold.indent_10
                    = "Do you work at #{a.name}?"
                  .even_smaller.indent_10
                    = auto_link("If so, click #{link_to 'here', organization_path(a)} to join the team!".html_safe)
                .pad_5
    - else
      %li
        %h4
          = auto_link("Step 1: Check out #{link_to @recipient.user.organizations.last.name, organization_path(@recipient.user.organizations.last)}".html_safe)
    %li
      %h4
        = auto_link("Step 2: Setup your #{link_to 'personal profile', edit_user_path(current_user)}".html_safe)
    %li
      %h4
        = "Step 3: Start making connections with professional Travel Planners"
  %p
    = "We have spent countless hours to ensure that iTourSmart is a tool that will increase your productivity, make your life easier, and hopefully bring a smile to your face once in a while.  That said, we are always looking for ways to improve. So, if something doesn't work, doesn't do what you want it to do, or you can think of an improvement to be implemented in the future - just click the link for 'support' in the title bar above and let us know."
  %p
    = "Enjoy,"
  %p
    = closing[rand(closing.length)]

app/views/recipients/fancybox_show.html.haml
%table#fancybox.smaller
  %tr
    %td.right.bold(width = "2px")
      From:
    %td
      = @recipient.note.is_sysmessage == true ? image_tag("/images/its_blue.gif", :alt => "logo", :height => "38", :width => "213") : @recipient.note.sender.full_name
  %tr
    %td.right.bold
      Subject:
    %td
      = @recipient.note.subject
  %tr
    %td.right.bold
      To:
    %td
      - for @receiver in @recipient.note.recipients
        = @receiver.user.try(:full_name)
  %tr
    %td.right.bold
      Received:
    %td
      = distance_of_time_in_words(@recipient.created_at, Time.now) + " ago"
      = "(#{@recipient.note.occurred_at.strftime("%B %e, %Y %r %Z")})"

.block_quote.left
  = link_to "Reply", new_note_path(:sender_id => current_user.id, :recipient_id => @recipient.note.sender.id, :from => current_user.full_name, :to => @recipient.note.sender.full_name, :subject => "Re: #{@recipient.note.subject}", :body => @recipient.note.body ) if !@recipient.note.is_sysmessage
  = "|" if !@recipient.note.is_sysmessage
  = link_to "Delete", recipient_path, :method => :delete


%hr
#note_view_body.left.dark_text
  - if !@recipient.note.permalink
    :textile
      #{textilize(@recipient.note.body)}
  - else
    = render @recipient.note.permalink

app/views/recipients/index.html.haml
- title "Message Center"
#content_wrapper
  #full_col.shadow.dark_text
    .col_head
      %h2.float_left
        = "messages"
      .col_head_link

        = link_to_unless_current "inbox", recipients_path(:partial => "inbox")
        |
        = link_to_unless_current "notifications", recipients_path(:partial => "notifications")
        |
        = link_to_unless_current "sent", recipients_path(:partial => "sent")

      .right
        = link_to "Dashboard", dashboard_path
      .clear
    .block_quote
      - if params[:partial] == "sent"
        = render 'sent'
      - elsif params[:partial] == "inbox"
        = render 'inbox'
      - elsif params[:partial] == "notifications"
        = render 'notifications'

app/views/recipients/show.html.haml
- title "Message Detail"
#content_wrapper
  #main_col.shadow.dark_text
    .col_head
      %h2.float_left
        - unless @recipient.note.is_sysmessage
          =  "Message from #{@recipient.note.sender.try(:full_name)}"
        - else
          =  "Message from iTourSmart"
      .right
        = link_to "message center", :back
        = "|"
        = link_to "Dashboard", dashboard_path
      .clear
    .block_quote.left
      = link_to "Reply", new_note_path(:sender_id => current_user.id, :recipient_id => @recipient.note.sender.id, :from => current_user.full_name, :to => @recipient.note.sender.full_name, :subject => "Re: #{@recipient.note.subject}", :body => @recipient.note.body ) if !@recipient.note.is_sysmessage
      = "|" if !@recipient.note.is_sysmessage
      = link_to "Delete", recipient_path, :method => :delete
    .block_quote.left
      %table
        %tr
          %td(width = "1px")
            Subject:
          %td
            = @recipient.note.subject
        %tr
          %td
            To:
          %td
            - for @receiver in @recipient.note.recipients
              = @receiver.user.try(:full_name)
        %tr
          %td
            Received:
          %td
            = @recipient.note.occurred_at.strftime("%B %e, %Y %r %Z")
      %hr
      #note_view_body.left.dark_text
        - if !@recipient.note.permalink
          :textile
            #{textilize(@recipient.note.body)}
        - else
          = render @recipient.note.permalink
                      
#sidebar.justify
  = render 'generic/banner_1'
  = render 'generic/banner_2'
  .pad_10
  = render "generic/twitter"